name: Push to Production

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Pushing to remote repository
        run: |
          git remote add production ${{ secrets.REMOTE_PATH }}
          git checkout master
          git fetch --unshallow
          git push -u production master --force